# Generated by Django 5.1.3 on 2024-11-21 13:20

import django.core.validators
import vent_app.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10), vent_app.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z\\s]+$')], verbose_name='Nombre del cliente : '),
        ),
        migrations.AlterField(
            model_name='productos',
            name='caracteristicas_categoria',
            field=models.CharField(choices=[('Limpieza', 'Limpieza'), ('Bebidas', 'Bebidas'), ('Ropa', 'Ropa'), ('Varios', 'Varios'), ('Comidas', 'Comidas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10), vent_app.validadores.validacion_numeros]),
        ),
    ]
